name: CI - 02 IaC Security

on:
  push:
    paths:
      - '02-iac-security/**'
      - '.github/workflows/iac.yml'
  pull_request:
    paths:
      - '02-iac-security/**'
      - '.github/workflows/iac.yml'

permissions:
  contents: read
  security-events: write

concurrency:
  group: iac-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.6'
      - name: Terraform fmt (check)
        run: terraform -chdir=02-iac-security fmt -recursive -check
      - name: Terraform init
        run: terraform -chdir=02-iac-security/envs/dev init -backend=false
      - name: Terraform validate
        run: terraform -chdir=02-iac-security/envs/dev validate -no-color

  checkov:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip checkov
      - run: checkov -d 02-iac-security -o sarif --output-file-path checkov.sarif || true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

