name: CI - 02 IaC Security

on:
  push:
    paths:
      - '02-iac-security/**'
      - '.github/workflows/iac.yml'
  pull_request:
    paths:
      - '02-iac-security/**'
      - '.github/workflows/iac.yml'

permissions:
  contents: read
  security-events: write

concurrency:
  group: iac-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-validate:
    name: Terraform fmt & validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.6'

      - name: Terraform fmt (check)
        run: terraform -chdir=02-iac-security fmt -recursive -check

      - name: Terraform init (no backend)
        run: terraform -chdir=02-iac-security/envs/dev init -backend=false

      - name: Terraform validate
        run: terraform -chdir=02-iac-security/envs/dev validate -no-color

  checkov:
    name: Checkov (Terraform) - WARN ONLY
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: pip install --upgrade pip checkov

      - name: Run Checkov (SARIF)
        run: checkov -d 02-iac-security -o sarif --output-file-path checkov.sarif || true

      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

